# Generated by Django 4.2.6 on 2023-10-27 03:51

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=200)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='images/category_images')),
                ('category_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='product', unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(max_length=225)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.TextField()),
                ('product_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='product', unique=True)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ApiApp.product_category')),
                ('saved_by', models.ManyToManyField(related_name='Saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
