# Generated by Django 4.2.6 on 2023-10-27 04:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='category_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='category', unique=True),
        ),
    ]
